---
title: "Replication Assignment"
author: "Laura Brubaker-Wittman"
date: "12/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

First, I will load the {readr} package, to make loading in data much easier!

```{r}
library(curl)
```

Now to load my data from Group B:
```{r}
f <- curl("https://raw.githubusercontent.com/laurabw/laurabw-data-replication-assignment/master/Group%20B_ForLaura.csv")
Group_B <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(Group_B)
str(Group_B)
```

```{r}
Group_B$DURATION..MIN.
```

Let's do the same for Group G:

```{r}
f <- curl("https://raw.githubusercontent.com/laurabw/laurabw-data-replication-assignment/master/GroupG_ForLaura.csv")
Group_G <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(Group_G)
```

```{r}
Group_G$DURATION.MIN
```


Let's do some basic descriptive stats for these:

For Group B, let's find the mean encounter time:

```{r}
mean(Group_B$DURATION..MIN.)
```


```{r}
mean(Group_G$DURATION.MIN, na.rm = TRUE)
```

```{r}
wilcox.test(Group_B$DURATION..MIN., Group_G$DURATION.MIN, conf.int = TRUE)
```

